<a href="https://colab.research.google.com/github/Sautam05/Pandas/blob/main/Pandas_Data_Cleaning_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment - Data Cleaning

Easy to Moderate Level

## Q1. Find Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})

Output:
    Name    Age
0  False  False
1  False   True
2   True  False

In [1]:
# Write your code here
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Aman", "Riya", None],
    "Age": [21, np.nan, 25]
})

print(df.isnull())

    Name    Age
0  False  False
1  False   True
2   True  False

## Q2. Count Total Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})

Output:
Name    1
Age     1

In [7]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})
print(df.isnull().sum())

Name    1
Age     1
dtype: int64

## Q3. Fill Missing Age with 0

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})

Output:
   Name   Age
0  Aman  20.0
1   Raj   0.0

In [8]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})
df['Age'].fillna(0, inplace=True)
print(df)

   Name   Age
0  Aman  20.0
1   Raj   0.0

/tmp/ipykernel_1404/1593842533.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(0, inplace=True)

## Q4. Fill Missing City with 'Unknown'

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})

Output:
   Name     City
0  Aman   Bhopal
1   Raj  Unknown

In [9]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Raj"],
    "City": ["Bhopal", None]
})
df['City'].fillna("Unknown", inplace=True)
print(df)

   Name     City
0  Aman   Bhopal
1   Raj  Unknown

/tmp/ipykernel_1404/1868389858.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna("Unknown", inplace=True)

## Q5. Remove Rows Having Null Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})

Output:
   Name  Age
0  Aman   20
1   Raj   25

In [10]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})
print(df.dropna())

   Name  Age
0  Aman   20
1   Raj   25

## Q6. Convert Age Column into Float

Input:
df = pd.DataFrame({"Age":[20,25,30]})

Output:
20.0, 25.0, 30.0

In [12]:
# Write your code here
df = pd.DataFrame({"Age":[20,25,30]})
df['Age'].astype(float)

0    20.0
1    25.0
2    30.0
Name: Age, dtype: float64

## Q7. Replace Delhi with New Delhi

Input:
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})

Output:
New Delhi, Mumbai, New Delhi

In [13]:
# Write your code here
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})
df['City'].replace('Delhi','New Delhi', inplace=True)
print(df)

        City
0  New Delhi
1     Mumbai
2  New Delhi

/tmp/ipykernel_1404/2590397438.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].replace('Delhi','New Delhi', inplace=True)

## Q8. Replace Score 88 with 100

Input:
df = pd.DataFrame({
    "Score":[88,90,88,75]
})

Output:
100,90,100,75

In [14]:
# Write your code here
df = pd.DataFrame({
    "Score": [88,90,88,75]
})
df["Score"].replace(88,100, inplace=True)
print(df)

   Score
0    100
1     90
2    100
3     75

/tmp/ipykernel_1404/1334957349.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].replace(88,100, inplace=True)

## Q9. Drop City Column

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})

Output:
   Name
0  Aman
1   Raj

In [15]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Raj"],
    "City": ["Bhopal", "Indore"]
})
df.drop("City", axis=1, inplace=True)
print(df)

   Name
0  Aman
1   Raj

## Q10. Drop Row at Index 1

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})

Output:
   Name
0  Aman
2  Riya

In [23]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Riya"]
})
df.drop(index=1, axis=0, inplace=True)
print(df)

   Name
0  Aman
2  Riya

## Q11. Check Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
False, False, True

In [26]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Aman"]
})
df.duplicated()

0    False
1    False
2     True
dtype: bool

## Q12. Remove Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
   Name
0  Aman
1   Raj

In [29]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Raj", "Aman"]
})
df.drop_duplicates(inplace=True)
print(df)

   Name
0  Aman
1   Raj

## Q13. Mini Data Cleaning Task

Input:
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}

Task:
1. Fill missing Age with mean.
2. Remove duplicate rows.
3. Display final DataFrame.

In [33]:
# Write your code here
data = {
    "Name": ["Aman", "Raj", "Aman", None],
    "Age": [20,None,20,25],
    "City": ["Bhopal", "Delhi", "Bhopal","Indore"]
}
b = pd.DataFrame(data)
b["Age"].fillna(b["Age"].mean(), inplace=True)
b.drop_duplicates(inplace=True)
print(b)

   Name        Age    City
0  Aman  20.000000  Bhopal
1   Raj  21.666667   Delhi
3  None  25.000000  Indore

/tmp/ipykernel_1404/3418118426.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b["Age"].fillna(b["Age"].mean(), inplace=True)